name: ⚗️Check

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '1.23'
      - name: install
        run: |
          sudo apt update -y
          sudo apt install -y libc6-dev libglu1-mesa-dev libgl1-mesa-dev libxcursor-dev libxi-dev libxinerama-dev libxrandr-dev libxxf86vm-dev libasound2-dev pkg-config
          export
          sudo Xvfb -ac :99 -screen 0 1280x1024x24 > /dev/null 2>&1 &
      - name: build
        run: go build .
      - name: test
        run: go test ./... -v
      - name: genbg
        env:
          DISPLAY: :99
        run: |
          make genbg
          ls -al raw/bg
      - name: check diff
        run: git diff --exit-code
