name: Publish

on:
  workflow_dispatch:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v5

      - name: Build
        run: |
          git fetch --prune --unshallow
          ./scripts/build.sh

      - name: Check
        run: |
          ls -al ./wasm

      - name: Publish generated content to GitHub Pages
        if: github.ref == 'refs/heads/main'
        uses: JamesIves/github-pages-deploy-action@v4.7.3
        with:
          branch: gh-pages
          folder: wasm
